<h2>Noé állatotthon alapítvány</h2>
<img src="<?='./images/'.$rolunk['1']['kepforras']?>" alt="<?=$rolunk[1]['kepalt'] ?>">
<p>Budapest legnagyobb állatotthonaként 1992 óta végezzük a bajba jutott, megkínzott, balesetet szenvedett állatok mentését. 3,5 hektáros, 2009. évtől majdnem 8 hektáros állatmenhelyünk jelenleg közel ezer kutya, cica, malac, kecske, juh, strucc, nyuszi, tengerimalac, csirke, kacsa, liba, páva, vaddisznó, mosómedve, ormányos medve, borz, ló, póni, szamár, láma, díszmadár, galamb, varjú, teknős, és szarvasmarha átmeneti, vagy - sok esetben - végleges otthona. 2012. tavaszától pedig bajba jutott főemlősöknek is segítünk.</p>

<h3>A kezdetektől napjainkig</h3>
<p>A NOÉ Állatotthon Alapítvány Budapest máig legnagyobb állatmenhelye 1992 óta működik saját anyagi erőforrásainkból, és csak 2000-ben alakult alapítvánnyá, de azóta is normatív állami támogatás nélkül, önerőből és a támogatók jóvoltából tartja fent magát és látja el két-, három- és négylábú védenceit.</p>

<img src="<?='./images/'.$rolunk['2']['kepforras']?>" alt="<?=$rolunk[2]['kepalt'] ?>">
<p>Az állatotthont két lelkes fiatal, Zoli és Hédi hozta létre. Ők ketten a 90-es évek elején megálmodtak egy olyan világot, ahol minden állatnak joga van az élethez és minden állat kaphat egy második esélyt, legyen az kidobott kutya vagy levesbe való kakas. Évek alatt összespóroltak egy telekre valót, majd elkezdték befogadni a hontalan, bajba jutott állatokat, akik egyre csak jöttek és jöttek, végül már több százan voltak. Hédi és Zoli közben sokszor nélkülöztek, eladták családi örökségeiket, kölcsönöket vettek fel, barátoknál, családtagoknál laktak, de az állatoknak mindig jutott ennivaló és orvosi ellátás. Ez a mai napig sincs másképp; az utolsó családi ingatlant 2008 májusában adták el, hogy a menhely adósságait törleszteni tudják. Hédit később más felé vitte életútja, de Zoli azóta is óvja, védi, menti az állatokat. Családjával fent laknak az állatotthonban az állatokkal egy kis faházban, de azt mondják: nem bánják, csak az állatoknak jusson minden, ami kell.</p>

<p>Ha a kedves állatbarátok is úgy vélik, hogy közel 1000 befogadott kis védencünk megérdemli a támogatást, talán nemsokára lesz majd annyi adományozónk, hogy az állatotthon teljes fenntartását fedezni tudjuk a befolyó felajánlásokból.</p>
<p>Jelenleg évi kb. 120 millió forintra lenne szükségünk az állatok ellátásához, gyógyíttatásához, kezeléséhez és az állatotthon fenntartásához. További pénzekből tudnánk fejleszteni, bővíteni, további férőhelyeket, karanténokat, orvosi szobát kialakítani. Terveink között szerepel egy felnőtt kutya és kölyök kutya karantén létrehozása, valamint egy oktatóközpont kialakítása.</p>

<h3>Nálunk nincs altatás</h3>
<img src="<?='./images/'.$rolunk['3']['kepforras']?>" alt="<?=$rolunk[3]['kepalt'] ?>">
<p>Alapítványunk egyik legfontosabb alapelve, hogy minden élőlénynek joga van az élethez, ezért egyetlen állatot sem altatunk el (kivéve természetesen a súlyosan sérült, szenvedő menthetetleneket), legyen bár létszám fölötti, születési vagy szerzett testi hibás, öreg, élete végéig kezelésre, drága diétára szoruló vagy egyszerűen csak csúnyácska.</p>
<p>A "bicebócák", a "vaksik" is teljes életet élhetnek állatotthonunkban, ahol külön részleget alakítottunk ki az idős állatoknak és azoknak a kutyáknak, akik valamilyen korábbi trauma miatt nem képesek beilleszkedni kutyatársaik és az emberek közé.</p>
<p>Utóbbiak a "Lelkibeteg Udvar" lakói, akiket korábban bántalmaztak, megkínoztak és akiket a szakembereknek nem sikerült rehabilitálniuk olyan mértékben, hogy gazdához adhassuk őket.</p>

<h3>Állatmentés és egyéb tevékenységek</h3>

<p>Állatmentő szolgálatunk elsődleges célja az utak mentén elütött és sorsukra hagyott, vagy más módon bántalmazott, sérült állatok azonnali állatorvoshoz juttatása és megfelelő ellátásban való részesítése.</p>
<p>Gyakran riasztanak minket állatkínzások kapcsán is; ilyenkor nem csak az állatról kell gondoskodnunk, hanem arról is, hogy a bűncselekmény elkövetője ellen eljárás induljon.</p>
<p>Katasztrófacsoportunk folyamatosan rendelkezésre áll az állatokat sújtó természeti vagy ipari katasztrófák esetére; az Állatvédelmi Katasztrófamentő Csoport tagjaként aktívan részt vettünk például 2001 tavaszán a beregi, 2002 nyarán a dunai árvíz Budapestet és környező településeit érintő szakaszán és a Gemenci erdő vadjainak mentésénél is. De vezető szerepünk volt 2010-ben a "vörös iszap katasztrófa" helyszínén bajbajutott állatok mentésében is.</p>
<img src="<?='./images/'.$rolunk['4']['kepforras']?>" alt="<?=$rolunk[4]['kepalt'] ?>">
<p>Egyik legfontosabb célkitűzésünk az oktatási szférában való részvétel és a társadalom szemléletváltozásának elősegítése, a felelős állattartásra nevelés.</p>
<p>Ennek keretein belül 2004 tavaszától elindult Állatvédelmi Oktató Programunk, melynek részeként általános és középiskolás csoportok "kihelyezett" biológia óráikat állatotthonunkban tartják, illetve iskolanapokra, osztályfőnöki órákra látogatunk el állatorvosokkal. Fontosnak tartjuk, hogy már egész kis korban megkezdődjön a gyermekek állat- és természetszeretetre való nevelése, és hogy minden fiatal megismerkedhessen a felelős állattartás alapjaival, a kedvencként tartott állatok szükségleteivel, igényeivel.</p>
<p>Az állatok védelméért folytatott munkánk elismeréseképpen 2002. október 04-én a Magyar Újságírók Országos Szövetsége Természet és Állatvédő Szakosztálya állatotthonunkat az Év Állatotthona címmel jutalmazta, más állatvédő szervezetek szavazatainak bevonásával.</p>

<h3>Speciális programjaink</h3>
<img src="<?='./images/'.$rolunk['5']['kepforras']?>" alt="<?=$rolunk[5]['kepalt'] ?>">
<p>2004 tavaszán elindult egyik legnagyobb programunk, a MiniMenhely-projekt. A program egyedülálló kezdeményezés hazánkban, melynek célja a sintértelepekre került, altatásra ítélt és megkínzott állatok szervezett mentése, rehabilitációja és új gazdához juttatása.</p>
<p>A program keretében egy 10 kenneles "mini menhely részleg" épült fel 100%-ban önkéntes munkával állatotthonunk területén, a többi kenneltől teljesen elszeparáltan, ami azóta is folyamatosan fogadja a rászoruló kutyákat. Mostanra a Minimenhely kenneljeinek száma gyakorlatilag megtriplázódott, így egyre több rászorulón tudunk segíteni. A MiniMenhely-program alapítványunk eddigi legnagyobb költségvetéssel működő projektje, hiszen a sintértelepekről az esetek nagy százalékában betegen kerülnek ki az állatok és gyakran hónapokig tartó kezelést igényelnek, mielőtt beköltözhetnek a menhelyre, ahol önkéntesek és szakemberek végzik további - gyakran rengeteg időt és türelmet igénylő - testi-lelki rehabilitációjukat.</p>
<p>Bár a program eredetileg a fővárosi gyepmesteri telep kutyáinak mentésére jött létre, az elmúlt években tevékenysége jelentősen kibővült és jelenleg 25 vidéki gyepmesteri telepről is menti a rászoruló ebeket, különös tekintettel a balesetesen, sérülten, vemhesen és fogyatékkal bekerülő állatokra. Bővebb információ a program önálló weboldalán található, a www.minimenhely.hu címen.</p>
<p>2006 őszétől Boxer fajtamentő csoportot is "üzemeltetünk", mivel hazánkban e fajta mentésére még semmilyen más szerveződés nem volt. Hogy erre mekkora igény van, azt az is tanúsítja, hogy a csapat rengeteg megkeresést kap sintértelepeken, menhelyeken, rossz körülmények között szenvedő boxerekkel kapcsolatban; még Szerbiából és Romániából is mentettünk boxereket. Bővebben a programról: www.boxermentes.hu</p>
<p>A NOÉ Állatotthon Alapítvány Bulldog fajtamentő csoportja 2009. januárjában alakult, de a fajtamentés már korábban elkezdődött a fajtaszerető önkéntesek áldozatos munkájának és anyagi hozzájárulásának köszönhetően.</p>
<p>Az elmúlt évek bebizonyították, hogy a fajtamentő csoport munkájára nagy szükség van, hiszen a bulldogok - különösen az angol és francia bulldogok - már egy ideje "divatkutyának" számítanak. Ezzel pedig sajnos együtt jár a felelőtlen szaporítók tömeges megjelenése, az ellenőrizetlen állományokból származó genetikai rendellenességekkel, betegségekkel küzdő állatok nagyszámú megjelenése a piacon és ezzel együtt a menhelyeken, az utcán, a sintértelepeken.</p>
<p>A Bulldog fajtamentő csoport honlapja: <a href="http://www.bulldogmentes.hu/">http://www.bulldogmentes.hu/</a></p>

<p>A Csau-csau Fajtamentő Csoport hivatalosan 2009 májusában alakult. Igaz, hogy a csauk esetében is már sokkal korábban részt vett az alapítvány a bajba került kutyák mentésében és az évek során tapasztaltak bebizonyították számukra, hogy a fajtamentés megszervezésére itt is nagy szükség van.</p>
<p>A fajta adottságaiból következik, hogy a csau-csauk mentése nem könnyű feladat, hiszen a csauk un. "egygazdás" kutyák. Gazdájukat egy életre választják ki, hozzá minden körülmények között ragaszkodnak, éppen ezért a gazdájuktól való elszakadás gyakorlatilag sokkot jelent e nagyszerű állatok számára. Rengeteg energiát, türelmet és elszántságot igényel, hogy egy lelkileg megtört csau-csau újra bízni tudjon valakiben - emiatt a rehabilitációjukra szánt idő szükségszerűen jóval hosszabb, mint sok más kutyafajta esetében. Természetesen a következetes, szeretetteljes és türelmes viselkedés hatására ez a fajta is képes megnyílni és újra bizalmába fogadni az embert.</p>
<p>A Csau-csau fajtamentő csoport honlapja: <a href="http://www.csaucsaumentes.hu">http://www.csaucsaumentes.hu</a></p>

<p>A NOÉ Állatotthon Alapítvány Cane Corso Fajtamentő Csoportja 2009 tavaszán kezdte meg működését. Bár a cane corso egyelőre nem fordul elő tömegesen hazánkban, a fajta mégis egyre népszerűbb a családi kutyák rajongói körében. Ahogy a hazai állomány száma nő, úgy egyre gyakrabban fordul elő, hogy valamelyik cane corsonak sürgős segítségre van szüksége.</p>
<p>A fajtamentő csoport elsődleges célja, hogy az azonnali segítségre szoruló kutyákat megmentse, elhelyezésükről, kezelésükről, rehabilitációjukról gondoskodjon, majd szerető gazához juttassa őket.</p>
<p>A Cane Corso fajtamentő csoport honlapja: <a href="http://www.canecorsomentes.hu/">http://www.canecorsomentes.hu/</a></p>

<p>Látogassanak el rendszeresen honlapunkra, hiszen folyamatosan beszámolunk bajba jutott állatok mentéséről és rehabilitációjáról.</p>